### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by JamzumSum** [aioqzone/aioqzone#45]
__Fontconfig error: Cannot load default config file__ was raised when collecting data using `node-canvas`.

<details>

<summary>Log details here</summary>

```
Traceback (most recent call last):
  File "/app/app.pyz/aioqzone/api/loginman.py", line 50, in _new_cookie
    cookie = await login.login(await login.check())
  File "/app/app.pyz/qqqr/up/__init__.py", line 107, in login
    cookie = await self.login(await self.passVC(r), StatusCode.NeedCaptcha)
  File "/app/app.pyz/qqqr/up/__init__.py", line 167, in passVC
    d = await c.verify()
  File "/app/app.pyz/qqqr/up/captcha/__init__.py", line 263, in verify
    collect = await self.tdc.get_data()
  File "/app/app.pyz/qqqr/up/captcha/vm.py", line 56, in get_data
    return unquote((await self._js.eval("window.TDC.getData(!0)")).strip())
  File "/app/app.pyz/jssupport/execjs.py", line 121, in exec
    raise JsRuntimeError(p.returncode or 1, node, removesuffix(stderr.decode()))
jssupport.exception.JsRuntimeError: Fontconfig error: Cannot load default config file
```

</details>

**Comment by JamzumSum** [comment]
`apt install fontconfig` may fix.

**Comment by JamzumSum** [comment]
> `apt install fontconfig` may fix.

maybe we should document this
